travis:
  secure:
    BINSTAR_TOKEN: JiOrvNtHWld0dv4oiOmPlA9HFeCgN8NolJXDh3dXNuAlfqS/tjySX/QYz7L6ZmHTW7oPzLEDdKTZb1yDt0Rc3kAwBK3clXLbo/GxclRAv8Bw3LzvN77FknEv1Ft8QvStX8l7fWAGdXEIM1iuNd+X8yWVrBI2+Y/OhxfrIbsbjmBDZyVZABHPGJNRqDsXIRmsrbY9zcpjFwb0Rgg47uukbZBsuihHKr1e6pBg0yQGSe0NgavKWP1xGnDBiV3TVj0iQJtAeYoDyaXMlmah53g1DNr67napUmtEHoQ3HXNTbqk3uORi4AR+G5uBr/eWKM1j1VU/dM3Jc/p7W24w56i7ZiNNDZa7mNEPPKn0n+Bf0DmgSK16hjPBYMnSUDcFRAz1HW2Kvq8xY3Dop7k7jcZ0rW+ZTW5w9KlSKPuxrzXiVWLNzvUhCDKCfjRDuZJk3D1UPSoxxvEMlBZ/q/hlpPYq+gmkpA7FAJLz/9VZKbSYRd30Duxb7atttZZ6mpCeRqtxh0wdddyaKOQUypm25Fz8YD9K4CNu5ztSZQ2dXbTvF/FdIYgSxTtXJF0yLkVnRHbbLTCpZaPBzSSiRjoDCN1nHZcCZok/keb9tJyff2FHJUCHSIVPYFUypM9oBoZSnSQ6DL0FF9xKsQRHCTYk0i/emVGn8RNjEAVamPI+DEj94mY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
